### ISSUE TITLE
Unable to successfully start the web ui

### ISSUE THREAD

**Issue by stevelacy** [alexellis/faas#110]
I have attempted to manually start and run the stack without using the playground with a few issues when accessing the web ui.

## Steps to Reproduce (for bugs)

I built and started the stack with the shell scripts, then I attempted to load `http://localhost:8080` and got forever-loading empty request. 

1. `./build.sh`
2. `./deploy_stack.sh`
```
Deploying stack
Creating network func_functions
Creating service func_gateway
Creating service func_alertmanager
Creating service func_nodeinfo
Creating service func_markdown
Creating service func_decodebase64
Creating service func_wordcount
Creating service func_hubstats
Creating service func_prometheus
Creating service func_echoit
Creating service func_base64
Creating service func_webhookstash
```
3. 
 -  `curl localhost:8080/function/func_markdown/ -d "## Testing"`
 - `curl: (56) Recv failure: Connection reset by peer`

I inspected the docker network and got the ip for the gateway container, and accessed it via `http://<containerid>:8080`. I got a white page with just this text: `Select a function.`.

I also manually ran `docker-compose build` `docker-compose up` `docker-compose down` to see if raw compose was a possible solution. I checked but didn't see a particular version of docker that is required.

Am I doing something entirely wrong, or is there a step for setting up the network that I need to do first?
I read all the md files in the repo, your blog post referencing faas, and some of the linked gists without finding a particular solution. 

## Your Environment

* Docker version `version 17.06.0-ce, build 02c1d87`

* Operating System and version (e.g. Linux, Windows, MacOS):

Debian Linux 4.9.0-3-amd64

**Comment by stevelacy** [comment]
I got it to work by changing the build version of the gateway to the local image: https://github.com/alexellis/faas/blob/master/docker-compose.yml#L10 `latest-dev`.
Still some form of issue as I needed to change the image.

**Comment by alexellis** [comment]
Hi @stevelacy,

Thanks for your message. 

You may have an ipv4/ipv6 conflict on the name localhost in your hosts file such as:

```
cat /etc/hosts
127.0.0.1	localhost
::1		localhost ip6-localhost ip6-loopback
```

You can comment out the 2nd line, or use 127.0.0.1 or the IP address of your LAN/WAN connection instead.

Curl can also be forced into ipv4 mode with the `-4` flag.

`docker-compose` is not used for FaaS, but it does have a `docker-compose.yml` file which is used for creating the Docker stack, so `docker-compose up/down/build` are not going to be valid.

The tag 0.5.6 for the gateway image is working (I also re-tested it this morning), but you can switch out to a newer (master) version like you did by running ./build.sh and updating the image tag to: `latest-dev`.

Hope this helps. I'll close the issue for now since you have got up and running, but do re-open if you need to.

**Comment by stevelacy** [comment]
Thanks
