### ISSUE TITLE
Samples for persistent servers that are not started upon every request?

### ISSUE THREAD

**Issue by rcarmo** [alexellis/faas#23]
I'd like to see a function container that was not restarted upon every request, preferably something that would accept HTTP or that could talk to a message queue (Redis, MQTT, etc.)

**Comment by alexellis** [comment]
The container is persistent, but fungible (it may be recycled at any time).

The process inside the container is started on each request so that stdin/stdout can be used to pipe in / out the request and response. If you want a long running Redis server etc you can make that part of your stack, it won't be a function.

In terms of changing the behaviour - you can use any container as a function which accepts a HTTP POST on port 8080.

Can you give more details on your use case?

**Comment by rcarmo** [comment]
I want to have more efficient CPU/IO handling. Firing up a new runtime on a per-request basis is expensive (Java/Clojure particularly so, but Python can have longish startup times too as it gathers libraries).

Are there any samples that work with HTTP? I couldn't find any.

**Comment by alexellis** [comment]
If you take the HubStats function for instance, it has very straight-forward code because it doesn't have to factor in serving HTTP, that's part of the stack. So all sample functions handle HTTP POSTs.

Let's take the Python example.

If you wanted to take HubStats and make it sticky, you would have to implement a web server in Python listening to POST on the `/` route.

The Python flask library can provide a HTTP server. So from the route handler method you'd then read the body of the request, invoke the existing code then return the response as a body.

```
from flask import Flask
app = Flask(__name__)

@app.route('/')
def hello_world():
    return 'Hello, World!'
```

**Comment by alexellis** [comment]
@rcarmo did this help? It'd be great to see your FaaS functions if they're on Github

**Comment by rcarmo** [comment]
Oh, I've managed to get an instance running, but there's only so much free time...
