### ISSUE TITLE
Project: design logo / name

### ISSUE THREAD

**Issue by alexellis** [alexellis/faas#68]
A logo will be useful for promoting project. Currently underway with designer.

At the same time a new project name could be useful. FaaS sounds a lot like "fast" which was confusing in the US.

**Comment by bateramos** [comment]
I don't know the current status, but also think the Faas name is a little confusing in an already confusing topic (FaaS vs Serverless. What is the difference and things like that).
I think a good name for it could be something like  Everest, because, you know, it auto scale the functions. Its about scaling. Not very clever but its a suggestion. Don't now if you are accepting suggestions for names, this can be very personal.
Hope I helped in some way.

**Comment by alexellis** [comment]
The company Serverless Inc appears to be doing well even with a generic name. I'm still looking into a logo which may involve a new alias or name.

**Comment by macneib** [comment]
Generally, project maintainers select a animal, or thing that shares common traits with the project to imply similar qualities.  Perhaps you have some traits in mind already?

**Comment by alexellis** [comment]
We have a cut of the logo here:

https://blog.alexellis.io/introducing-functions-as-a-service/

**Comment by alexellis** [comment]
Thanks for the comments

**Comment by alexellis** [comment]
This is now widely known as OpenFaaS - www.openfaas.com. Closing issue.

**Comment by liampauling** [comment]
Mind sharing who the designer was for the logo? (big fan)
